# Generated by Django 5.1.5 on 2025-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=8)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
